name       : haskell-mintty
version    : 0.1.2
release    : 2
source     :
    - http://hackage.haskell.org/package/mintty-0.1.2/mintty-0.1.2.tar.gz : 7c8af77bcde4e9b54692e3761f41adf35a50664974ba77f2ba65ea2af9f950da
license    : BSD-3-Clause
component  : programming.haskell
summary    : A reliable way to detect the presence of a MinTTY console on Windows
description: |
    A reliable way to detect the presence of a MinTTY console on Windows
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
